In [1]:
## STEPS FOR BUILDING A PROJECT

#1. Raw Customer Data
#2. preprocessing
#3. Feauture engineering
#4. Scaling
#5. Train Test split
#6. Build ANN Model
#7. Train the ANN model
#8. save the model
#9. Deploy it on streamlit
#Customer stayed=0
#customer left=1

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [17]:
df = pd.read_csv("Churn_Modelling.csv")
print(df.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

In [6]:
with open("StandardScaler.pkl", "wb") as file:
     pickle.dump(StandardScaler, file)

In [7]:
# load the customer churn dataset.

data = pd.read_csv('Churn_Modelling.csv')

In [ ]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
## preprocessing the data

data = data.drop(['RowNumber','CustomerId', 'Surname'], axis=1)

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
## Featuring Engineering

label_encoder_gender = LabelEncoder()

In [10]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
Onehotencoder_geography = OneHotEncoder()

geo_encoder = Onehotencoder_geography.fit_transform(data[['Geography']]).toarray()

geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [ ]:
geo_encoded_df = pd.DataFrame(
    geo_encoder,
     columns=Onehotencoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [ ]:
data = pd.concat(
    [
        data.drop(['Geography'], axis=1),
        geo_encoded_df
    ],
    axis=1
)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
with open("LabelEncoder_Gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("Onehotencoder_geography.pkl","wb") as file:
    pickle.dump(Onehotencoder_geography, file)
print("Encoder saved successfully.")

Encoder saved successfully.

In [18]:
StandardScaler = StandardScaler
StandardScaler.fit(df[['CreditScore','Age','Tenure','Balance','NumOfProducts','EstimatedSalary']])
with open("StandardScaler.pkl", "wb") as f:
    pickle.dump(StandardScaler, f)

In [ ]:
# X = Features INPUT
# Y = Output/Target
Y = 'EstimatedSalary'

In [ ]:
X = data.drop(
    "EstimatedSalary", axis=1
)

Y = data["EstimatedSalary"]

## For the regression workflow, X represents the input features and y represents
#  the EstimatedSalary as the target variable.


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
## In training data "fit.transform" is used
## In Testing data ".Transform" is used

Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

In [ ]:
## Building regression model

model = Sequential([

tf.keras.Input(shape=(X_train.shape[1],)),
      Dense(64,activation='relu'),
      Dense(32,activation='relu'),
      Dense(1,activation='linear')
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
## Compile
model.compile(optimizer='Adam',loss='mse',metrics=['mae'])
history = model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=50,
    batch_size=32,
    verbose=1
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13382657024.0000 - mae: 100372.2266 - val_loss: 13002264576.0000 - val_mae: 98494.0547
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13213221888.0000 - mae: 99525.6953 - val_loss: 12665197568.0000 - val_mae: 96790.6172
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12617184256.0000 - mae: 96556.5078 - val_loss: 11811471360.0000 - val_mae: 92472.0547
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11451098112.0000 - mae: 90757.2734 - val_loss: 10396544000.0000 - val_mae: 85326.2969
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9774100480.0000 - mae: 82371.9688 - val_loss: 8590751744.0000 - val_mae: 76297.3203
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7860595712.0000 - mae: 72874.2422 - val_loss: 6748494336.0000 - val_mae: 67121.2109
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6094639616.0000 - mae: 63983.6602 - val_loss: 5237251584.0000 - val_mae: 59561.5977
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4775853056.0000 - mae: 57168.9023 - val_loss: 4252426752.0000 - val_mae: 54533.4297
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3998543104.0000 - mae: 53147.4570 - val_loss: 3762115584.0000 - val_mae: 52004.7383
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3638215168.0000 - mae: 51273.0977 - val_loss: 3571953408.0000 - val_mae: 51119.6055
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3502722048.0000 - mae: 50599.6016 - val_loss: 3511631104.0000 - val_mae: 50869.1523
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3453108736.0000 - mae: 50332.9570 - val_loss: 3487206912.0000 - val_mae: 50772.4492
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3428886016.0000 - mae: 50211.3594 - val_loss: 3471847936.0000 - val_mae: 50705.6250
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3412997376.0000 - mae: 50132.7031 - val_loss: 3458383616.0000 - val_mae: 50641.7695
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3400785664.0000 - mae: 50070.2734 - val_loss: 3448130048.0000 - val_mae: 50590.0156
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3389853696.0000 - mae: 50009.4609 - val_loss: 3437680128.0000 - val_mae: 50534.6875
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3380712960.0000 - mae: 49958.9648 - val_loss: 3428024832.0000 - val_mae: 50484.3750
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3372833024.0000 - mae: 49917.7266 - val_loss: 3420967168.0000 - val_mae: 50445.8477
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3365691648.0000 - mae: 49881.1758 - val_loss: 3412629504.0000 - val_mae: 50404.7656
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3359495424.0000 - mae: 49849.6328 - val_loss: 3408520192.0000 - val_mae: 50382.5195
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3354298112.0000 - mae: 49825.2422 - val_loss: 3400312832.0000 - val_mae: 50336.1445
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3349459456.0000 - mae: 49797.0898 - val_loss: 3395601664.0000 - val_mae: 50317.2461
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3344680448.0000 - mae: 49772.4219 - val_loss: 3391955200.0000 - val_mae: 50298.7031
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3340860416.0000 - mae: 49750.6094 - val_loss: 3387008512.0000 - val_mae: 50270.3594
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3337287936.0000 - mae: 49729.1016 - val_loss: 3383208448.0000 - val_mae: 50249.3359
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3333606656.0000 - mae: 49710.3320 - val_loss: 3380317952.0000 - val_mae: 50237.6133
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3330871040.0000 - mae: 49694.8633 - val_loss: 3376641280.0000 - val_mae: 50217.8711
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3327993344.0000 - mae: 49676.5195 - val_loss: 3374716672.0000 - val_mae: 50207.8672
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3325661184.0000 - mae: 49663.4922 - val_loss: 3372467200.0000 - val_mae: 50197.6875
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3322949632.0000 - mae: 49646.1836 - val_loss: 3370544128.0000 - val_mae: 50190.6172
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3320723712.0000 - mae: 49629.4922 - val_loss: 3370223360.0000 - val_mae: 50191.4922
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3319283456.0000 - mae: 49622.1719 - val_loss: 3366547712.0000 - val_mae: 50169.4570
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3317534976.0000 - mae: 49611.9141 - val_loss: 3365560064.0000 - val_mae: 50166.4492
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3316152320.0000 - mae: 49603.2227 - val_loss: 3363455744.0000 - val_mae: 50153.1914
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3314207488.0000 - mae: 49592.8320 - val_loss: 3362512384.0000 - val_mae: 50152.4492
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3312535296.0000 - mae: 49580.8516 - val_loss: 3361428736.0000 - val_mae: 50147.9492
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3311420672.0000 - mae: 49573.5039 - val_loss: 3360701952.0000 - val_mae: 50141.5742
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 3310298368.0000 - mae: 49571.8281 - val_loss: 3360816128.0000 - val_mae: 50148.2852
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3309063680.0000 - mae: 49559.1016 - val_loss: 3359074816.0000 - val_mae: 50135.9531
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3308235520.0000 - mae: 49556.3711 - val_loss: 3359438592.0000 - val_mae: 50137.0195
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3307062784.0000 - mae: 49544.7305 - val_loss: 3359109632.0000 - val_mae: 50140.1992
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3306159872.0000 - mae: 49542.0469 - val_loss: 3358143232.0000 - val_mae: 50136.6953
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3304660480.0000 - mae: 49526.7266 - val_loss: 3359286272.0000 - val_mae: 50146.9961
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 3304015104.0000 - mae: 49526.6953 - val_loss: 3357956352.0000 - val_mae: 50138.7969
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3303031552.0000 - mae: 49523.8086 - val_loss: 3357325056.0000 - val_mae: 50135.0117
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3302164992.0000 - mae: 49513.5312 - val_loss: 3355966720.0000 - val_mae: 50123.8008
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3301748992.0000 - mae: 49509.2617 - val_loss: 3355549184.0000 - val_mae: 50120.7891
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3300941568.0000 - mae: 49505.0898 - val_loss: 3355901696.0000 - val_mae: 50122.7578
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3300480000.0000 - mae: 49499.4062 - val_loss: 3354780928.0000 - val_mae: 50120.1328
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3299081984.0000 - mae: 49485.9414 - val_loss: 3355124480.0000 - val_mae: 50121.2031

In [ ]:
## Evaluate

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"RMSE: {rmse}")
print(f"R2 Score: {r2}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
MAE: 50121.204099999995
RMSE: 57923.436472083704
R2 Score: -0.016318414169929074

In [ ]:
## Save and reload
model.save('Salary_model.keras')
print("Model saved as Salary_model.keras")

from tensorflow.keras.models import load_model
loaded_model = load_model('Salary_model.keras')
print("Model reloaded successfully!")

loaded_model.evaluate(X_test, y_test)

Model saved as Salary_model.keras
Model reloaded successfully!
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3355124480.0000 - mae: 50121.2031

[3355124480.0, 50121.203125]

In [ ]:
data.columns
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

QUESTION ANSWERS
Q1.Why did we remove sigmoid from the output layer?
ANS:Sigmoid limits output to 0-1 for classification.Salary is continuous,so we need linear activation.

Q2.Why is Binary Cross-Entropy not suitable here?
ANS:BCE is for 0/1 classification.This is regression,so we use MSE/MAE.

Q3.What does MAE mean in salary units?
ANS: MAE is in dollars.MAE of 10k means average error is $10k.

Q4.If RMSE is much larger than MAE, what might that suggest?
ANS:It means that there are large outlier with big errors.

Q5.What are the limitations of predicting salary from this classroom dataset?
ANS:Small synthetic dataset,missing key features like job role and education,won't generalize to real world.